### ISSUE TITLE
Create Open API

### ISSUE THREAD

**Issue by devanada** [Sistem-Manajemen-E-Wallet/BE-E-Wallet#4]

**Comment by anggraanutomo** [comment]
Openapi

- [ ] boilerplate #8 
- [ ] users
- [ ] merchants

**Comment by ezabintangr** [comment]
> Openapi
> 
> * [x]  boilerplate [feat:openAPI #8](https://github.com/Sistem-Manajemen-E-Wallet/BE-E-Wallet/pull/8)
> * [x]  users
> * [x]  merchants
> * [x]  transactions
> * [ ]  products
> * [x]  wallets
> * [ ]  top-ups
> * [x]  histories
